-- CREATE VIEW view_applicationForms AS 
SELECT
    BUS.BU_NAME,BUS.BU_PRESIDENT,CONCAT(TP.TP_FNAME,' ',' ',TP.TP_MNAME,' ',TP.TP_LNAME) TAX_PAYERNAME,BUS.BU_LOCATION,BUS.BU_CONTACT,CONCAT(AR.AR_FNAME,' ',AR.AR_MNAME,' ',AR.AR_LNAME) AUTH_REPNAME,AR.AR_HOME_ADDRESS, BN.BN_NAME, OT.OT_NAME, AP.AP_TYPE,AP.AP_DATE,ATC.AT_UNIFIED_FILE_NAME,AP.AP_ID,ATC.AT_ID
FROM
    lgu_r_business BUS
INNER JOIN lgu_r_business_nature BN ON
    BN.BN_ID = BUS.BN_ID
INNER JOIN lgu_r_ownership_type OT ON
    OT.OT_ID = BUS.OT_ID
INNER JOIN lgu_r_bp_application AP ON
    AP.BU_ID = BUS.BU_ID
INNER JOIN lgu_r_taxpayer TP ON
	TP.TP_ID = BUS.TP_ID
INNER JOIN lgu_r_bu_ar BUxAR ON
	BUxAR.BU_ID = BUS.BU_ID
INNER JOIN lgu_r_authorize_rep AR ON
	AR.AR_ID = BUxAR.AR_ID
INNER JOIN lgu_r_attachments ATC ON
	ATC.AP_ID = AP.AP_ID